### ISSUE TITLE
Information Centre: Change order of entries

### ISSUE THREAD

**Issue by balcse** [micado-eu/migrant_application#100]
Order of entries is arbitrary and not comprehensible, keyword sorting has to be reasonable; maybe alphabetical

**Comment by ivchicano** [comment]
Sorting of the information centre and the events page are sorted by most recent first (date of creation/translation), to keep the most recent information or events first. We should discuss if this sorting is correct in the next call or in this issue.

This however does not apply if you use the search bar, which sorts by the closest matches first.
