### ISSUE TITLE
Readspeaker function works only on titles

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#102]
The readspeaker function works only on titles, not on description or other content. 
The users who need this support, might need it also on the description and other content.

**Comment by gioppoluca** [comment]
Can you talk to check on how to add only on the migrant component? @GiuseppeCSI @ivchicano

**Comment by ivchicano** [comment]
I can reuse some of the components already created for text to speech and add them to the descriptions component (GlossaryEditorViewer)

**Comment by ivchicano** [comment]
Added readspeaker buttons to descriptions in https://github.com/micado-eu/migrant_application/commit/9cf9bbd7a60149685dddee1dacec8302a2c2ce44
Might need refinement but it is a start. Closing this issue.
