### ISSUE TITLE
On phone: Common words - Description is empty

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#104]
All descriptions of common words and events are empty on phone view, visible on desktop, same issue when you change the language (i tested with Dutch)
![Empty description glossary on phone ](https://user-images.githubusercontent.com/75615204/101622246-166f8c00-3a17-11eb-90bc-936c5d19a337.PNG)

**Comment by ivchicano** [comment]
Looks like this bug only happens on iphone/safari, looking for a fix

**Comment by ivchicano** [comment]
This should be fix now, please try again

**Comment by AnneliesVerroken** [comment]
I get the same view as before, only the titles are visible in  common words, no descriptions.

I checked on Iphone, IOS 14.3,  browser safari, have cleared cache first.

Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: maandag 4 januari 2021 15:13
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] On phone: Common words - Description is empty (#104)


This should be fix now, please try again

**Comment by ivchicano** [comment]
I can't seem to reproduce this problem in Iphone 7 plus with iOS 14.3, the descriptions display perfectly for me. I suggest clearing the website stored data (Settings >Safari > Advanced > Website data)
![micadoiphone1](https://user-images.githubusercontent.com/46921761/106740915-50c26780-661b-11eb-8a34-be63eb70507b.jpeg)
![micadoiphone2](https://user-images.githubusercontent.com/46921761/106740920-515afe00-661b-11eb-8fa2-e987939f31d6.jpeg)

**Comment by AnneliesVerroken** [comment]
Is ok for me as well. Shall I close?
