### ISSUE TITLE
possible enhancement: put a clickable layer over a weblink

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#106]
Links to websites outside of the app can be terribly long or technical, a clickable layer on top can enhance the user experience for user with less developed internet skills.

**Comment by gioppoluca** [comment]
Does the editor allow for entering a link?

**Comment by ivchicano** [comment]
Yes, you can copy and paste a link and it detects it as a clickable link.
![FatSRUEnMD](https://user-images.githubusercontent.com/46921761/101750300-1b901200-3acf-11eb-8b72-66d6f384fb7a.gif)
If this is confusing, we can add a button to the menu for adding links or a menu bubble like here: https://tiptap.dev/links

**Comment by AnneliesVerroken** [comment]
The link itself is not that confusing, it is more that some links can be very very long and "ugly" , which takes a lot of space on the screan of a phone, taking awayunder a clickabl overall neatness and clearness of the view for the user.

In the application "welkom in Antwerpen" we hid these links under a word, that appears in lightblue, so it is clear that word is clickable.


I just wondered if this might be an idea here as well.

Kind regards,

Annelies


Annelies Verroken
Medewerker E-inclusie

Atlas - Integratie en Inburgering Antwerpen



________________________________
Van: Iván Chicano <notifications@github.com>
Verzonden: donderdag 10 december 2020 10:08:28
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] possible enhancement: put a clickable layer over a weblink (#106)


Yes, you can copy and paste a link and it detects it as a clickable link.
[FatSRUEnMD]<https://user-images.githubusercontent.com/46921761/101750300-1b901200-3acf-11eb-8b72-66d6f384fb7a.gif>
If this is confusing, we can add a button to the menu for adding links or a menu bubble like here: https://tiptap.dev/links

**Comment by ivchicano** [comment]
This functionality has been added to the text editors. Closing.
![LO6NFottuL](https://user-images.githubusercontent.com/46921761/102356559-a67c7b00-3fad-11eb-82b8-ccf8c9eea195.gif)
