### ISSUE TITLE
Guided proces: steps: cost of step: enable more text?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#107]
Sometimes there are steps with a cost attached that is not clear and simple. Maybe there are 2 possibilities depending on someone's situation, or maybe there is a price range.... between 0 - 100Euro for exemple. 
Now you can only enter a digit.

**Comment by gioppoluca** [comment]
This is a request for the PA application and not the migrant

**Comment by AnneliesVerroken** [comment]
Oh sorry, of course, I will make it again in the correct place!


Annelies Verroken
Medewerker E-inclusie

Atlas - Integratie en Inburgering Antwerpen



________________________________
Van: Luca Gioppo <notifications@github.com>
Verzonden: donderdag 10 december 2020 10:01:51
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] Guided proces: steps: cost of step: enable more text? (#107)


This is a request for the PA application and not the migrant
