### ISSUE TITLE
Guided processes: if a guided process is not translated, it shows as empty text

### ISSUE THREAD

**Issue by ivchicano** [micado-eu/migrant_application#112]
The text shows as empty if you change the language of the app to one that isn't translated. It should either show the default language or not show at all.
![chrome_JCApXmCaqx](https://user-images.githubusercontent.com/46921761/102209585-3f899400-3ed1-11eb-9723-f5b4a93510af.png)

**Comment by gortazar** [comment]
I also noticed that if you go into the detailed page of any process, all the fields are empty.

Maybe it could be a good idea to show the original language until the translation is ready. Otherwise I think this is a bit confusing.

**Comment by GiuseppeCSI** [comment]
The fetch looks for the selected language and, if it's not there, picks the default language. The problem right now is that the query is done on the translation tables, where there are entries for every language (the other languages are a blank string) and it  should be done on the translation prod tables where, when you publish, only the base language and translated languages are present. This needs to be modified in the backend, @gioppoluca
