### ISSUE TITLE
View of an event: "Tag" is visible on Iphone view, not on desktop

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#113]
When viewing an event, the view on Ophone has 1 more field "Tag", emty. This is not visible on desktop. Not sure which is the correct view, I suppose the "tag" is not relevant info for the migrant and should not be visible?
![Migr app_Event_phone view](https://user-images.githubusercontent.com/75615204/102227044-68b61e80-3ee9-11eb-98fd-4b8e1bfae96d.png)
![MIG app_Event_view](https://user-images.githubusercontent.com/75615204/102227074-6e136900-3ee9-11eb-9602-0e018d1a8216.PNG)

**Comment by ivchicano** [comment]
This should be fix now, please try again

**Comment by AnneliesVerroken** [comment]
Ok on my phone.

Thanks!

Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: maandag 4 januari 2021 15:13
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] View of an event: "Tag" is visible on Iphone view, not on desktop (#113)


This should be fix now, please try again
