### ISSUE TITLE
Uploaded image : not visible in mobile view 

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#116]
An uploaded image is visible on desktop, but not on mobile ( tested on Iphone). I have checked it for event, glossary and information centre, all have the same result.

![Migr app_phone view_no image](https://user-images.githubusercontent.com/75615204/102489614-0175a700-406e-11eb-93f6-a27efb127fb5.jpg)

**Comment by ivchicano** [comment]
This should be fix now, please try again

**Comment by AnneliesVerroken** [comment]
On my phone, no images are visible in the description, no description alltoghether.
This goes for information center, event, common words and integration step by step.

I have cleared cache, use Iphone with IOS 14.3


Van: Iván Chicano [mailto:notifications@github.com]
Verzonden: maandag 4 januari 2021 15:14
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] Uploaded image : not visible in mobile view (#116)


This should be fix now, please try again

**Comment by ivchicano** [comment]
I can't seem to reproduce this problem in Iphone 7 plus with iOS 14.3, the descriptions display perfectly for me.
![micadoiphone1](https://user-images.githubusercontent.com/46921761/106740915-50c26780-661b-11eb-8a34-be63eb70507b.jpeg)
![micadoiphone2](https://user-images.githubusercontent.com/46921761/106740920-515afe00-661b-11eb-8fa2-e987939f31d6.jpeg)

**Comment by AnneliesVerroken** [comment]
Is now fine on my phone as well. I see the images that are uploaded. Shall I close?
