### ISSUE TITLE
View model - guided processes - to close window I used ESC - what to use on smartphone???

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/migrant_application#118]
![image](https://user-images.githubusercontent.com/61241645/102975536-89d9c900-4500-11eb-953a-08a60d91c6b6.png)

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/102975977-2a2fed80-4501-11eb-9d81-6fc3f2d99c45.png)

**Comment by JohnAntwerp** [comment]
When I hit the back button on the smartphone it navigates back to the overview listing of the guided processes instead of to the current page I'm at within the guided process. On the webpage on computer I hit the ESC button to get rid of the displayed model of an EID document.

**Comment by JohnAntwerp** [comment]
I was able to squeeze the window between thumb and point finger...that opened a window where I could hit the x button making the view model windo close and going back to the guided process page...It would be better to have an X button on the window...Initially I expected the box containing the page number to be the X button...

**Comment by GiuseppeCSI** [comment]
You can close the popup window by clicking outside the popup area (this should work on smartphone too). We could consider adding an X so that you can also close the popup by clicking on that

**Comment by GiuseppeCSI** [comment]
I've added an X to close the popup
