### ISSUE TITLE
Information centre content - Existenzminimum - not loading on smartphone

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/migrant_application#119]
![image](https://user-images.githubusercontent.com/61241645/102977181-ee962300-4502-11eb-8b4a-6add4e7c60d7.png)

Content on computer is loading correctly...

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/102977378-33ba5500-4503-11eb-9b1d-9e088cc5d7b2.png)

Content not visible on iPhone, giving error message.

**Comment by ivchicano** [comment]
This should be fix now, please try again
