### ISSUE TITLE
Guided proces_steps_how to get back to first overview of graph and description?

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#127]
When opening a step of aguided process, there is no way to go back to the first view when you opened this guided process, with all steps closed.  Could there be a possibility to "close"the steps?  Might be linked to issue  #117 to put description above the graph.
A combination of both would be ideal: description on top, and a way to close the step you are in so you go back to the first view.

**Comment by GiuseppeCSI** [comment]
I've now moved the description of the process below the title. Also, you can now "close" a step by clicking on it a second time. If everything works fine, please close this issue.

**Comment by AnneliesVerroken** [comment]
Hi Guiseppe,

That is great! When I open the migr app on my phone, and I open a guided process, I don’t see these changes yet.
Am I too fast to check?

Have a good evening,
Annelies

Annelies Verroken
E-inclusie
Tel. 03 334 41 40

Atlas - integratie & inburgering Antwerpen



Op 27 jan. 2021 om 17:50 heeft GiuseppeCSI <notifications@github.com> het volgende geschreven:

﻿

I've now moved the description of the process below the title. Also, you can now "close" a step by clicking on it a second time. If everything works fine, please close this issue.

**Comment by GiuseppeCSI** [comment]
I've checked and it seems the changes are not yet online.  It could take some time, so maybe it's better to check tomorrow

**Comment by AnneliesVerroken** [comment]
Hi,

I’ve checked just now |(9:45am), seems the changes are not online yet.



Van: GiuseppeCSI [mailto:notifications@github.com]
Verzonden: woensdag 27 januari 2021 18:12
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] Guided proces_steps_how to get back to first overview of graph and description? (#127)


I've checked and it seems the changes are not yet online. It could take some time, so maybe it's better to check tomorrow

**Comment by GiuseppeCSI** [comment]
I've checked from pc and i can see them. I think you have to delete your browser's cache

**Comment by AnneliesVerroken** [comment]
Works!
Also on mobile.

Thanks!

Van: GiuseppeCSI [mailto:notifications@github.com]
Verzonden: donderdag 28 januari 2021 12:59
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] Guided proces_steps_how to get back to first overview of graph and description? (#127)


I've checked from pc and i can see them. I think you have to delete your browser's cache

**Comment by GiuseppeCSI** [comment]
Closing since it has been done
