### ISSUE TITLE
Step by step_ result page_Order of the user categories appear in random order

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#129]
Minor remark: The order of the user categories is not aligned on the results page. Sometimes you see A - R -M, sometimes R-M-A.. this enforces confusion for the user. The more uniformity, the better. Now they appear in the order they were added in the pa app. 
![Order icons in result list not alligned](https://user-images.githubusercontent.com/75615204/106116596-61259e80-6152-11eb-9f58-a14dd28ed553.PNG)

**Comment by GiuseppeCSI** [comment]
The categories should now appear always in the same order. If this works, please close this issue

**Comment by AnneliesVerroken** [comment]
Hi,

Thank you! Hard to test right asap, because content has to go through weblate before being published, but I ll close the issue for now and get back to it in the future if problems arise?

Have a good weekend

Annelies

Van: GiuseppeCSI [mailto:notifications@github.com]
Verzonden: vrijdag 29 januari 2021 15:03
Aan: micado-eu/migrant_application
CC: Annelies Verroken; Author
Onderwerp: Re: [micado-eu/migrant_application] Step by step_ result page_Order of the user categories appear in random order (#129)


The categories should now appear always in the same order. If this works, please close this issue
