### ISSUE TITLE
Text to speech_ language adapted and enable option to stop

### ISSUE THREAD

**Issue by AnneliesVerroken** [micado-eu/migrant_application#130]
The text to speech is currently only in English. So when default language of the migr app is in Spanish for example, the speech reads Spanish in an English way.
I understand this is still a work in progress but must not be forgotten by the time of the usertests. 

According to the current WCAG guidelines (where we require level AA as public authority), when there is text to speech support, it should be possible for the user to stop the audio at any moment. 
This is not possible yet.

**Comment by GiuseppeCSI** [comment]
I've made some temporary fixes. You can now stop the text to speech by clicking again on the button you used to activate it. Also, the voice's language is now based on the language of the app. This part still needs to be improved though, but for testing it would work just fine. Also, these changes should take a little more time to come online. Once you can chech that it works, please close this issue

**Comment by gioppoluca** [comment]
we will work on a more complete solution

**Comment by AnneliesVerroken** [comment]
Sure! 
This temporary fix works fine for now.
