### ISSUE TITLE
How to manage past events / courses? 

### ISSUE THREAD

**Issue by RIEMAL** [micado-eu/migrant_application#136]
What will happen with events or courses once they are outdated? Will their entries be deleted automatically? That would be the preferred scenario as it will be extra work for the PAs and CSOs to manually delete the entries.

**Comment by RIEMAL** [comment]
I am for less clutter :), so for option 2. But a connected question to this is: Is there the option to chose for an event whether it is reoccuring?

**Comment by ivchicano** [comment]
At the moment it is not possible, it could be implemented but it would take a significant amount of effort that I am not sure we have the time for it (as it implies modifications on the PA and NGO apps as well)

**Comment by RIEMAL** [comment]
I see, thanks for the info! Then, option 1 is better in my opinion, because authors could reuse the infos of unpublished events. I will take the question to the next WP5 meeting next week and come back with a decision. Ok?

**Comment by ivchicano** [comment]
I think that's a good idea

**Comment by RIEMAL** [comment]
We discussed it today and voted for option 1 (unpublish) to be able to use the information again. 
We assume that it is possible to manually delete the data if the event will not happen again in the backlog. Is that correct?

**Comment by ivchicano** [comment]
Yes that is correct, you can delete any event using the designated button in the PA application

**Comment by RIEMAL** [comment]
Super, thank you!

**Comment by ivchicano** [comment]
This has been implemented.
For technical references, see:
https://github.com/micado-eu/backend/commit/b5dc548276c32a37084e1876cf1b8563fa2f0a17
https://github.com/micado-eu/pa_application/commit/1f5974fbe48083f1dba0e0c0419ebc9b818a749d
