### ISSUE TITLE
Define icons for document types

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#14]
As for mail

**Comment by gioppoluca** [comment]
Here a first draft from Synio.

![MICADO Graphic Elements 0 1](https://user-images.githubusercontent.com/1488715/74725393-190db480-523e-11ea-9dd8-9a6ca851baf1.png)

**Comment by gioppoluca** [comment]
@carmenmunteanu  can we have the single files?
For the powered by can we also have a horizontal one (on footers it could be either too small ro too high)

For the stamp we need the "post-stamp" concept since sometime you are required to glue a poststamp of some value on official document.

Also all document should have same aspect ratio.

**Comment by carmenmunteanu** [comment]
Graphical elements are saved on NextCloud:
https://micado.hcu-hamburg.de/nextcloud/apps/files/?dir=/02.%20Consortium/02.%20Work%20Packages/WP4/02.%20WP4%20work%20and%20exchange%20folder/App%20icons%20and%20graphics&fileid=116214

**Comment by gioppoluca** [comment]
@carmenmunteanu can you also produce a 600x600 version?

**Comment by carmenmunteanu** [comment]
@gioppoluca Please be more specific...which one should also be in 600x600?

**Comment by gioppoluca** [comment]
@carmenmunteanu sorry, the "M" ones and the data repositories.
Also can you produce a "powered by" horizontal and not vertical? on the footer it occupies a bit too much space
