### ISSUE TITLE
Automatic Links: remove linebreaks

### ISSUE THREAD

**Issue by balcse** [micado-eu/migrant_application#150]
Now if there is an automatic link in the glossary enty, a linebreak will be generated right after, even if it is in the middle of the sentence

**Comment by balcse** [comment]
<img width="345" alt="linebreak_glossary" src="https://user-images.githubusercontent.com/15378003/118516844-fb781500-b736-11eb-9fe3-3eb25e8e2e8a.PNG">

**Comment by ivchicano** [comment]
Can you copy here the text that has this problem? It will be helpful for debugging the issue

**Comment by balcse** [comment]
this is how it looks like in the PA-app:




anderes Wort für >**Bundesagentur für Arbeit

**

Die Arbeitsagentur

(früher: Arbeitsamt) ist Ansprechpartnerin für Bürgerinnen und Bürger und Unternehmen für Themen des **Arbeits- und Ausbildung

smarktes**.

Wichtigeste Aufgaben der Agentur für Arbeit sind:

- Vermittlung von Lehrstellen und Jobs

- Berufsberatung

- Förderung der Berufsausbildung

Menschen ohne Arbeit beantragen zusätzlich bei der Arbeitsagentur

ihr Arbeitslosengeld. Auch >**Aktivierungsgutschein

e** vergibt die Arbeitsgentur.

Dies ist die [Homepage](arbeitsagentur

.de/en/welcome>) der Agentur für Arbeit in Hamburg.

**Comment by balcse** [comment]
and here ist the link to the migrant app entry: https://migrants.micadohh.online/glossary?id=127

**Comment by trtstm** [comment]
We are also having similar problems.

@balcse do you have problems with bold text not being bold anymore and empty lines disapearing?

**Comment by balcse** [comment]
Yes, sometimes instead of bold texts we get some with an asterisk, like above (like "**Bundesagentur für Arbeit**" in the example above)

**Comment by balcse** [comment]
A comment by Mert on when it appears: _"When I edit an entry and if this entry has existing bold phrases, they are marked with asterisk in the new edited version. If I delete whole text and rewrite it assigning words bold again. Then, it worked in most cases"_

**Comment by ivchicano** [comment]
All the issues mentioned should be fixed now, please reopen this issue or open another one if you find more bugs with the editor

**Comment by trtstm** [comment]
Is this fixed in just the migrant app or also the PA?

**Comment by ivchicano** [comment]
It should be fixed in all apps. The problem was when saving the content in the PA or CSO apps (if curious, the HTML to Markdown conversion was adding a line break after <span> tags, which are used by the references), so the content previously saved before this patch will still look broken, but rewriting the content now should work correctly.
