### ISSUE TITLE
First title on welcome page is spoken in wrong language

### ISSUE THREAD

**Issue by webdevotion** [micado-eu/migrant_application#177]
The first title on the welcome page is spoken in English while I am using Dutch, other items are spoken in the correct ( Dutch ) language.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/50583/141102196-21b5a31d-e10f-44ce-b273-ab8b6d800895.png">

Might be related to #176.

**Comment by webdevotion** [comment]
Turns out that the string that is being displayed, is not the same string that is used by the Text to Speech feature.

**Comment by GiuseppeCSI** [comment]
Yes, I changed that so now the they are both the same
