### ISSUE TITLE
use closed card sorting methods for process design?

### ISSUE THREAD

**Issue by rosathoneick** [micado-eu/migrant_application#23]
[IMG_3969](https://user-images.githubusercontent.com/43851466/75894343-5c6a4480-5e34-11ea-9d10-2d0f25ff9255.JPG)
as we have seen in the fedasil presentation in Atlas in Antwerp on March 4, 2020

**Comment by gioppoluca** [comment]
Please try to do similar activity we need to have words or sentences linked to topic to train chatbot
