### ISSUE TITLE
Send some snapshot of the fedasil application

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#41]
I downloaded the fedasil application but outside Belgium it does not work.
We need a couple of screenshot to guide UX people to understand what we aim.
Please get a home screen, a screen for the glossary, and one for the description of a process.
Thanks

**Comment by janblonde** [comment]
Homepage
<img width="854" alt="Schermafbeelding 2020-03-11 om 11 40 41" src="https://user-images.githubusercontent.com/11859651/76409030-2249f700-638e-11ea-9a79-7e6f408546f6.png">

Procedures
<img width="853" alt="Schermafbeelding 2020-03-11 om 11 41 26" src="https://user-images.githubusercontent.com/11859651/76409053-2b3ac880-638e-11ea-9674-3c87500a59a7.png">
<img width="850" alt="Schermafbeelding 2020-03-11 om 11 41 51" src="https://user-images.githubusercontent.com/11859651/76409085-355cc700-638e-11ea-86cc-d20ff6383452.png">
<img width="855" alt="Schermafbeelding 2020-03-11 om 11 42 22" src="https://user-images.githubusercontent.com/11859651/76409109-3c83d500-638e-11ea-93c6-5c9265182d8f.png">

Inline glossary
<img width="861" alt="Schermafbeelding 2020-03-11 om 11 43 35" src="https://user-images.githubusercontent.com/11859651/76409146-47d70080-638e-11ea-8e49-38c494c2a95c.png">

Let me know if you needs some more.
