### ISSUE TITLE
Design the navigation flow of the application

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#43]
Starting and using the diagram from Jowie we need to have a detailed flow of the application.

in the diagram we will have to write also the routes that we will use in vue in this way we will have the needed detail for development and also know all the "jumps" from one page to the other

I place here the link to the diagram:
https://micado.hcu-hamburg.de/nextcloud/apps/drawio/118616

**Comment by gioppoluca** [comment]
Some comments on the diagram flow:
- we do not need the page for the language selection  @janblonde can you post here a screenshot of the way that fedasil application do the change language? If I remember well that application had a button in the footer that generated a dropdown with all the languages written in the correct language; I would go for this option since it will be present in all the application
- I do not like the info portal overview page; unless we think to list only the "most looked" processes or the newest one those lists will be just a subset and we need to understand how to select which goes in the page; having both content on the same page could be a bit too much and generating confusion; I would prefer to have one-page - one-content
- the general info are much like "articles" of a blog we need to define a structure of the content (an image, some description, a link ...
- we need to have a better navigation from the list to the detail of both the processes and general info
- the processes have also a secondo level of detail since each step has the details of documents needed etc.
- I would not use the logical division of "info portal" and user portal" (since this add a click level) but I'd place in their place the list of potential content "processes" "articles/info" wallet and things like the wallet just appear if you are logged in
- we need a way, in the splash page to convey the message that if you log in you get better content and features so please consider a splash page (with the checkbox not to show it again)
- integration task does not have a graph only a task list (think of it as a normal todo list the only difference is that is not the user that mark the task as completed but other actors).
- login page will not be served by VUE nor the consent management so be aware that we could need to adapt to a much more simple coding on that; I still have to understand how the consent is managed after the first time. so let us keep this part undefined for the moment

**Comment by JowieXiang** [comment]
Thanks Luca for the feedback. I have adjusted the wire-frames accordingly.

**Comment by gioppoluca** [comment]
we need a pager for the step description in the process flow or a better wireframe for an accordion like detail but the steps are selecterd from the graph and there is the list of needed document and produced document so is quite a number of info ,
That part have to be designed for a better UX since at the moment in the pilot is not appealing

**Comment by gioppoluca** [comment]
On the change language page I think that we need to consider if using flags since not always those represent a language but only one of the main country where that language is spoken.
Fedasil adopted only the textual representation.

**Comment by JowieXiang** [comment]
> we need a pager for the step description in the process flow or a better wireframe for an accordion like detail but the steps are selecterd from the graph and there is the list of needed document and produced document so is quite a number of info ,
> That part have to be designed for a better UX since at the moment in the pilot is not appealing

**Comment by JowieXiang** [comment]
> we need a pager for the step description in the process flow or a better wireframe for an accordion like detail but the steps are selecterd from the graph and there is the list of needed document and produced document so is quite a number of info ,
> That part have to be designed for a better UX since at the moment in the pilot is not appealing

Hi Luca, I am not sure if I understand this comment. But I have added a 'click to jump to corresponding step' interaction in the wireframe. We can maybe talk about this in detail during our next weekly meeting.

**Comment by JowieXiang** [comment]
> On the change language page I think that we need to consider if using flags since not always those represent a language but only one of the main country where that language is spoken.
> Fedasil adopted only the textual representation.

Added a new design for this. Thanks for the comment :)

**Comment by gioppoluca** [comment]
@Leo-Moertenhuber @JowieXiang remember that we also have ratings for most of the entities.

Migrant an rate a process or a step or an info
