### ISSUE TITLE
Design the DB schema

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#44]
In the link below there is the first draft of the schema we need to evolve it, consolidate and agree upon, defining the data types and check thast we are not missing information.

Once wee have this  we can use PostgREST to have a first set of API to use straightforward and publish tham through API manager to be ready to use.

We can also generate some views for better usability.
https://dbdiagram.io/d/5e68e5264495b02c3b881b1e

**Comment by gortazar** [comment]
[Here's a link](https://www.vertabelo.com/blog/data-modeling-for-multiple-languages-how-to-design-a-localization-ready-system/) where several approaches for DB design for content translation are presented. I'd go for 3 or 3b or 4.

**Comment by gioppoluca** [comment]
I also followed that approach, as you can see in the schema there are tables with just the attributes that are not translatable and than the table of the translatable terms

I would also add some views where we already have the query that get the content of the join so that we can have an API that collect the proper rows filtering on language:
/glossary/en/  = select from view where lang = 'en'

This way from the application we can call the api with the configutation of the required language.

**Comment by gioppoluca** [comment]
@gortazar @janblonde can you send some feedback within tomorrow on the initial structure, we need to give some conmsolidated data structure to the UX team for getting the detailed design of application

**Comment by gioppoluca** [comment]
@janblonde please we have this problem:
- users are managed by WSO2 identity server (WSO2 IS) on its own postgresql DB schema.
- Micado apps are running on a second DB schema
- we need to refer to the users managed in the WSO2 IS since we do not want to duplicate or to have ETL running around, can you suggest a proper way of doing this?

**Comment by gortazar** [comment]
@gioppoluca what's the meaning of task in the db diagram? I assume we have processes, that in turn have steps. So I don't understand what tasks represent. Can you please clarify? 

In the wireframes, "task" is explicitly used in the menu to bring the migrant to the list of processes. But I think the term process and task are interchangeable, and we shall choose one or the other.

**Comment by gioppoluca** [comment]
task is for the "smart todo list" that the PA assign to the migrant.
The process is the description of the steps to follow to reach a goal.
Tasks are the list of "todo" that the PA assign to an individual.
As John showed us they have a set of standard tasks they assign.
We need to have a list of tasks available and to allow the PA to assign a specific set to a subject.

**Comment by gortazar** [comment]
Ah, ok. It's clear now. No relation with the processes.

Shall we include pictures/icons to tasks/glossary terms/processes/steps? If so, where would these images be stored? All the applications might need to access them.

**Comment by gioppoluca** [comment]
only topics and document_type have an icon and we will store it in base64 in the DB (since is an icon)

the general info could have a picture like a blog post, we can store also that as base64 in the DB

**Comment by janblonde** [comment]
Hi, I agree with Luca on the definition of task vs. process he proposes. However I do think there is a relation between task and process: task could be for example: "get a driver's licence", which is linked to the process steps of how to get that driver's license. Agree?

I will get back with feedback on initial structure and wso2 tomorrow (tuesday)

**Comment by gioppoluca** [comment]
> Hi, I agree with Luca on the definition of task vs. process he proposes. However I do think there is a relation between task and process: task could be for example: "get a driver's licence", which is linked to the process steps of how to get that driver's license. Agree?
> 
> I will get back with feedback on initial structure and wso2 tomorrow (tuesday)

Yes that is right, do you think that we cloud link the task with a specific process or with a potential list of proper processes(there could be a process slightly different based on the migrant status), in this case we can add a many to many table and a drag and drop option when editing the task.

**Comment by janblonde** [comment]
Hi Luca, yes - I think a many to many table is a good idea here.

**Comment by janblonde** [comment]
In response to an earlier question on WS02 users (see quoted text), I see at least two options:

1. Use Postgres Foreign Data Wrappers (https://wiki.postgresql.org/wiki/Foreign_data_wrappers) to access the user data in WSO2 identity server. A contra argument for this is that it is probably not a good idea to directly access the WSO2 data structure, as it creates a direct dependency to the internal WSO2 data-structure.

2. Use the WSO2 identity server API's (https://is.docs.wso2.com/en/latest/develop/calling-admin-services/). Ofcourse, if we want to refer to this data from a postgres database table, some duplication (and synchronisation) of data will be necessary.

> @janblonde please we have this problem:
> 
> * users are managed by WSO2 identity server (WSO2 IS) on its own postgresql DB schema.
> * Micado apps are running on a second DB schema
> * we need to refer to the users managed in the WSO2 IS since we do not want to duplicate or to have ETL running around, can you suggest a proper way of doing this?

**Comment by janblonde** [comment]
In response to the question on a localization approach, our preference is approach 4. The only contra argument for this approach is that the db schema gets a bit messy as it is overflooded with translation tables, but from a technical standpoint this approach should work well.

> [Here's a link](https://www.vertabelo.com/blog/data-modeling-for-multiple-languages-how-to-design-a-localization-ready-system/) where several approaches for DB design for content translation are presented. I'd go for 3 or 3b or 4.

**Comment by gioppoluca** [comment]
> In response to an earlier question on WS02 users (see quoted text), I see at least two options:
> 
>     1. Use Postgres Foreign Data Wrappers (https://wiki.postgresql.org/wiki/Foreign_data_wrappers) to access the user data in WSO2 identity server. A contra argument for this is that it is probably not a good idea to directly access the WSO2 data structure, as it creates a direct dependency to the internal WSO2 data-structure.
> 
>     2. Use the WSO2 identity server API's (https://is.docs.wso2.com/en/latest/develop/calling-admin-services/). Ofcourse, if we want to refer to this data from a postgres database table, some duplication (and synchronisation) of data will be necessary.
> 
> 
> > @janblonde please we have this problem:
> > 
> > * users are managed by WSO2 identity server (WSO2 IS) on its own postgresql DB schema.
> > * Micado apps are running on a second DB schema
> > * we need to refer to the users managed in the WSO2 IS since we do not want to duplicate or to have ETL running around, can you suggest a proper way of doing this?

I believe that we can go for differente schema in the same DB and using search path enabling the micado user to read WSO2 table so to be able to create foreign keys.
I do not really want to enter the mess of aligning 2 different DB or going to API calls for this.
There is also the chance to use secondary user store, but I'm asking WSO2 support for better info.
Unless we have better ideas I think that isolating usihng different schemas is a good solution giving the read visibility to micado user, is a good compromise.

You find user tables from WSO2 in the schema for reference; mind that they use a composite primary key and the web tool we use is not capable of managind that so have just created 2 sepatare references.

**Comment by gortazar** [comment]
There is something in the document part that looks strange to me:

A step links to a step_document, that has a id_document that links to a document_type (?), but the field should then be id_document_type. Also I don't know why it links to a document_type and not to a document (in which case id_document would indeed be the FK of the document id).

**Comment by gortazar** [comment]
Also step_translation field step should be renamed to step_title (if that's the meaning), otherwise it seems to be the FK that points to step.id (whereas in reality it is the id of step_translation what maps to step.id).

**Comment by gortazar** [comment]
user_types and user_types_translation could be joined in a single table as we did for the glossary table. user_types has only an id.

**Comment by gioppoluca** [comment]
No we need user_type have a single ID with multiple translation and we need to have FK relations just with the ID.
The glossary table is one that has no join with other so we could do the merge since we can have the key  done id && lang
