### ISSUE TITLE
describe the integration steps for proper example

### ISSUE THREAD

**Issue by gioppoluca** [micado-eu/migrant_application#8]
We discussed with Valeria that in Antwerp you need to set a task list for migrant to help them in their integration, these are things like "attend to a language course" etc.

I need to know if:
1. these task are standard and equal for all
2. have an example of a task list for a typical migrant (in case is different person by person)

Please use this issue to work on this

**Comment by gioppoluca** [comment]
We also need to understand how we want to process the validation of the completion of each task.

I suppose that the migrant cannot certify the completion by himself, but rely on NGO or PA for this; I'm expecting classical validation process: ask for validation to subject - ok/ko - iterate.

Is this correct?

**Comment by janblonde** [comment]
I posed this question to John and Valeria, as I don't have this information myself. Will keep you posted on progress.
