### ISSUE TITLE
Information centre - functionality is missing 

### ISSUE THREAD

**Issue by RIEMAL** [micado-eu/migrant_application#92]
I can't find the information centre in the migrants' app anymore. Probably because currently someone is working on it, but just to make sure, I am adding it here.

**Comment by JohnAntwerp** [comment]
I have the same question. Added information 'aanvraag leefloon' (request financial support) via PA functionality but unable to view the content in migrant section.

![image](https://user-images.githubusercontent.com/61241645/98940169-de922900-24ea-11eb-83ea-64a3cf4085d6.png)

**Comment by ivchicano** [comment]
Seems like a bug related to the PA settings not enabling the information centre, but I can't edit it there. @GiuseppeCSI can you fix it?
