### ISSUE TITLE
Created events in PA-app not visible in MIGRANT-app

### ISSUE THREAD

**Issue by JohnAntwerp** [micado-eu/migrant_application#94]
![image](https://user-images.githubusercontent.com/61241645/98970461-4149eb80-2510-11eb-9e19-3ea0c361a2e7.png)

Nothing visible in Migrant app...see below for the 2 created events Payday in category 'Betaalkalender'...

![image](https://user-images.githubusercontent.com/61241645/98970779-9f76ce80-2510-11eb-999f-eceb336dd2f2.png)

**Comment by ivchicano** [comment]
I see them in migrant app, do you still not see them?
![chrome_XAQiT8UKWl](https://user-images.githubusercontent.com/46921761/99045437-9d088900-2591-11eb-8e84-1b17289bfe05.png)

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/99046050-8282df80-2592-11eb-879e-357e0efebd95.png)

I still have same screen...you see them...the letters are black...I now see that there are rows in the window...and if I double click on them they open...they are there but 'invisible'.

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/99046298-d8578780-2592-11eb-824f-2e1b57595db2.png)

If I double click on a row this is what I see...the title of the event is not visible

**Comment by ivchicano** [comment]
What language do you have selected on the migrant application?

**Comment by JohnAntwerp** [comment]
![image](https://user-images.githubusercontent.com/61241645/99047327-58cab800-2594-11eb-8367-db56b8fba608.png)

Nederlands...I switched to English to find below result

![image](https://user-images.githubusercontent.com/61241645/99047500-94fe1880-2594-11eb-91f3-c5dcc62f1de3.png)

Events are visible in all languages...but if you do not fill content in one of the languages you will see nothing on your screen?

Is this designed to work like this? If so the issue can be closed I guess...It means from a PA-user perspective that if you create an event content should be made available in all languages? Or, if contant is not filled for a language it should not be shown?

**Comment by ivchicano** [comment]
I agree it should not show if you do not fill the content, I will fix that. Another option is defaulting to english when showing content, but that could have complications if english is not selected as a language by the PA.

**Comment by JohnAntwerp** [comment]
I agree it should only show in the language for which you created content. Thanks for your replies.

**Comment by ivchicano** [comment]
Fixed by commit https://github.com/micado-eu/migrant_application/commit/49de33616e4088b915da5a66ad24629abbda2589 , closing
